/*
  # Populate spells table with spell data

  1. New Data
    - Populate `spells` table with comprehensive spell data
    - Include all spell properties: name, level, school, casting_time, range, components, duration, description, higher_levels, classes
    - Generate proper UUIDs for each spell

  2. Data Structure
    - Each spell has complete D&D 5e information
    - Components stored as JSONB with V, S, M properties
    - Classes stored as text array
    - Proper French translations and descriptions

  3. Coverage
    - Cantrips (level 0) through 9th level spells
    - All major spell schools represented
    - Multiple classes covered (Barde, Clerc, Druide, Ensorceleur, Magicien, Paladin, Rôdeur, Sorcier)
*/

-- Insert comprehensive spell data
INSERT INTO spells (id, name, level, school, casting_time, range, components, duration, description, higher_levels, classes) VALUES
-- Cantrips (Level 0)
('550e8400-e29b-41d4-a716-446655440001', 'Lumière', 0, 'Évocation', '1 action', 'Contact', '{"V": true, "S": false, "M": "une luciole ou de la mousse phosphorescente"}', '1 heure', 'Vous touchez un objet qui ne fait pas plus de 3 mètres dans chaque dimension. Jusqu''à la fin du sort, l''objet émet une lumière vive dans un rayon de 6 mètres et une lumière faible sur 6 mètres supplémentaires. La lumière peut être de n''importe quelle couleur de votre choix. Couvrir complètement l''objet avec quelque chose d''opaque bloque la lumière. Le sort se termine si vous le lancez de nouveau ou si vous le révoquez par une action.', NULL, '{"Barde", "Clerc", "Ensorceleur", "Magicien"}'),

('550e8400-e29b-41d4-a716-446655440002', 'Prestidigitation', 0, 'Transmutation', '1 action', '3 mètres', '{"V": true, "S": true, "M": null}', 'Jusqu''à 1 heure', 'Ce sort est un tour de magie mineur que les lanceurs de sorts novices utilisent pour s''entraîner. Vous créez un des effets magiques suivants à portée : vous créez instantanément un effet sensoriel inoffensif, comme une pluie d''étincelles, une bouffée de vent, de faibles notes musicales ou une odeur étrange. Vous allumez ou éteignez instantanément une chandelle, une torche ou un petit feu de camp. Vous nettoyez ou salissez instantanément un objet ne faisant pas plus de 30 centimètres cubes. Vous refroidissez, réchauffez ou aromatisez jusqu''à 30 centimètres cubes de matière non vivante pendant 1 heure. Vous faites apparaître une couleur, une petite marque ou un symbole sur un objet ou une surface pendant 1 heure. Vous créez un bibelot non magique ou une image illusoire qui peut tenir dans votre main et qui dure jusqu''à la fin de votre prochain tour.', NULL, '{"Barde", "Ensorceleur", "Sorcier", "Magicien"}'),

('550e8400-e29b-41d4-a716-446655440003', 'Flèche acide', 0, 'Invocation', '1 action', '27 mètres', '{"V": true, "S": true, "M": null}', 'Instantané', 'Une flèche scintillante d''énergie acide file vers une créature à portée. Effectuez une attaque de sort à distance contre la cible. Si elle touche, la cible subit 1d4 dégâts d''acide immédiatement et 1d4 dégâts d''acide à la fin de son prochain tour. Si vous ratez, l''acide éclabousse la cible et elle subit la moitié des dégâts initiaux et aucun dégât à la fin de son prochain tour.', 'Les dégâts du sort augmentent de 1d4 quand vous atteignez le niveau 5 (2d4), le niveau 11 (3d4) et le niveau 17 (4d4). Les deux jets de dégâts augmentent.', '{"Ensorceleur", "Magicien"}'),

-- Level 1 Spells
('550e8400-e29b-41d4-a716-446655440004', 'Projectile magique', 1, 'Évocation', '1 action', '36 mètres', '{"V": true, "S": true, "M": null}', 'Instantané', 'Vous créez trois fléchettes scintillantes d''énergie magique. Chaque fléchette touche une créature de votre choix que vous pouvez voir à portée. Une fléchette inflige 1d4 + 1 dégâts de force à sa cible. Les fléchettes frappent simultanément et vous pouvez les diriger contre une seule créature ou plusieurs.', 'Quand vous lancez ce sort en utilisant un emplacement de sort de niveau 2 ou supérieur, le sort crée une fléchette de plus pour chaque niveau d''emplacement au-delà du niveau 1.', '{"Ensorceleur", "Magicien"}'),

('550e8400-e29b-41d4-a716-446655440005', 'Soins', 1, 'Évocation', '1 action', 'Contact', '{"V": true, "S": true, "M": null}', 'Instantané', 'Une créature que vous touchez récupère un nombre de points de vie égal à 1d8 + votre modificateur de caractéristique d''incantation. Ce sort n''a aucun effet sur les morts-vivants ou les créatures artificielles.', 'Quand vous lancez ce sort en utilisant un emplacement de sort de niveau 2 ou supérieur, les soins augmentent de 1d8 pour chaque niveau d''emplacement au-delà du niveau 1.', '{"Barde", "Clerc", "Druide", "Paladin", "Rôdeur"}'),

('550e8400-e29b-41d4-a716-446655440006', 'Bouclier', 1, 'Abjuration', '1 réaction', 'Personnelle', '{"V": true, "S": true, "M": null}', '1 round', 'Une barrière invisible de force magique apparaît et vous protège. Jusqu''au début de votre prochain tour, vous avez un bonus de +5 à la CA, y compris contre l''attaque qui a déclenché ce sort. Si cette attaque vous rate, vous ne subissez aucun dégât.', NULL, '{"Ensorceleur", "Magicien"}'),

('550e8400-e29b-41d4-a716-446655440007', 'Armure de mage', 1, 'Abjuration', '1 action', 'Contact', '{"V": true, "S": true, "M": "un morceau de cuir tanné"}', '8 heures', 'Vous touchez une créature volontaire qui ne porte pas d''armure, et une force magique protectrice l''entoure jusqu''à la fin du sort. La CA de base de la cible devient 13 + son modificateur de Dextérité. Le sort se termine si la cible enfile une armure ou si vous le révoquez par une action.', NULL, '{"Ensorceleur", "Magicien"}'),

('550e8400-e29b-41d4-a716-446655440008', 'Détection de la magie', 1, 'Divination', '1 action', '9 mètres', '{"V": true, "S": true, "M": null}', 'Concentration, jusqu''à 10 minutes', 'Pendant la durée du sort, vous ressentez la présence de magie dans un rayon de 9 mètres autour de vous. Si vous ressentez de la magie de cette manière, vous pouvez utiliser votre action pour voir une aura faible autour de toute créature ou objet visible dans la zone qui porte de la magie, et vous apprenez son école de magie, le cas échéant.', NULL, '{"Barde", "Clerc", "Druide", "Magicien", "Paladin", "Rôdeur", "Ensorceleur", "Sorcier"}'),

('550e8400-e29b-41d4-a716-446655440009', 'Bénédiction', 1, 'Enchantement', '1 action', '9 mètres', '{"V": true, "S": true, "M": "une aspersion d''eau bénite"}', 'Concentration, jusqu''à 1 minute', 'Vous bénissez jusqu''à trois créatures de votre choix à portée. Chaque fois qu''une cible effectue un jet d''attaque ou un jet de sauvegarde avant la fin du sort, la cible peut lancer un d4 et ajouter le résultat au jet d''attaque ou de sauvegarde.', 'Quand vous lancez ce sort en utilisant un emplacement de sort de niveau 2 ou supérieur, vous pouvez cibler une créature supplémentaire pour chaque niveau d''emplacement au-delà du niveau 1.', '{"Clerc", "Paladin"}'),

('550e8400-e29b-41d4-a716-446655440010', 'Charme-personne', 1, 'Enchantement', '1 action', '9 mètres', '{"V": true, "S": true, "M": null}', '1 heure', 'Vous tentez de charmer un humanoïde que vous pouvez voir à portée. Il doit effectuer un jet de sauvegarde de Sagesse, et il le fait avec un avantage si vous ou vos compagnons le combattez. S''il rate son jet de sauvegarde, il est charmé par vous jusqu''à la fin du sort ou jusqu''à ce que vous ou vos compagnons lui fassiez du mal. La créature charmée vous considère comme un ami. Quand le sort se termine, la créature sait qu''elle a été charmée par vous.', 'Quand vous lancez ce sort en utilisant un emplacement de sort de niveau 2 ou supérieur, vous pouvez cibler une créature supplémentaire pour chaque niveau d''emplacement au-delà du niveau 1. Les créatures doivent se trouver à 9 mètres les unes des autres quand vous les ciblez.', '{"Barde", "Druide", "Ensorceleur", "Sorcier", "Magicien"}'),

-- Level 2 Spells
('550e8400-e29b-41d4-a716-446655440011', 'Invisibilité', 2, 'Illusion', '1 action', 'Contact', '{"V": true, "S": true, "M": "un cil enrobé de gomme arabique"}', 'Concentration, jusqu''à 1 heure', 'Une créature que vous touchez devient invisible jusqu''à la fin du sort. Tout ce que la cible porte ou transporte est invisible tant que c''est sur sa personne. Le sort se termine si la cible attaque ou lance un sort.', 'Quand vous lancez ce sort en utilisant un emplacement de sort de niveau 3 ou supérieur, vous pouvez cibler une créature supplémentaire pour chaque niveau d''emplacement au-delà du niveau 2.', '{"Barde", "Ensorceleur", "Sorcier", "Magicien"}'),

('550e8400-e29b-41d4-a716-446655440012', 'Toile d''araignée', 2, 'Invocation', '1 action', '18 mètres', '{"V": true, "S": true, "M": "un peu de toile d''araignée"}', 'Concentration, jusqu''à 1 heure', 'Vous invoquez une masse de toiles d''araignée épaisses et collantes en un point que vous pouvez voir à portée. Les toiles remplissent un cube de 6 mètres d''arête à partir de ce point pendant la durée du sort. Les toiles sont un terrain difficile et obscurcissent légèrement leur zone.', NULL, '{"Ensorceleur", "Magicien"}'),

-- Level 3 Spells
('550e8400-e29b-41d4-a716-446655440013', 'Boule de feu', 3, 'Évocation', '1 action', '45 mètres', '{"V": true, "S": true, "M": "une petite boule de guano de chauve-souris et de soufre"}', 'Instantané', 'Une traînée brillante jaillit de votre doigt pointé vers un point que vous choisissez à portée, puis explose en un rugissement de flammes. Chaque créature dans une sphère de 6 mètres de rayon centrée sur ce point doit effectuer un jet de sauvegarde de Dextérité. Une cible subit 8d6 dégâts de feu si elle rate son jet de sauvegarde, ou la moitié de ces dégâts si elle le réussit.', 'Quand vous lancez ce sort en utilisant un emplacement de sort de niveau 4 ou supérieur, les dégâts augmentent de 1d6 pour chaque niveau d''emplacement au-delà du niveau 3.', '{"Ensorceleur", "Magicien"}'),

('550e8400-e29b-41d4-a716-446655440014', 'Foudre', 3, 'Évocation', '1 action', '30 mètres', '{"V": true, "S": true, "M": "un peu de fourrure et une baguette d''ambre, de cristal ou de verre"}', 'Instantané', 'Un éclair forme une ligne de 30 mètres de long et 1,50 mètre de large partant de vous dans une direction de votre choix. Chaque créature sur la ligne doit effectuer un jet de sauvegarde de Dextérité. Une créature subit 8d6 dégâts de foudre si elle rate son jet de sauvegarde, ou la moitié de ces dégâts si elle le réussit.', 'Quand vous lancez ce sort en utilisant un emplacement de sort de niveau 4 ou supérieur, les dégâts augmentent de 1d6 pour chaque niveau d''emplacement au-delà du niveau 3.', '{"Ensorceleur", "Magicien"}'),

('550e8400-e29b-41d4-a716-446655440015', 'Contresort', 3, 'Abjuration', '1 réaction', '18 mètres', '{"V": false, "S": true, "M": null}', 'Instantané', 'Vous tentez d''interrompre une créature en train de lancer un sort. Si la créature lance un sort de niveau 3 ou inférieur, son sort échoue et n''a aucun effet. Si elle lance un sort de niveau 4 ou supérieur, effectuez un test de caractéristique d''incantation. Le DD est égal à 10 + le niveau du sort. En cas de réussite, le sort de la créature échoue et n''a aucun effet.', 'Quand vous lancez ce sort en utilisant un emplacement de sort de niveau 4 ou supérieur, l''interruption est automatique si le niveau du sort est inférieur ou égal au niveau de l''emplacement utilisé.', '{"Ensorceleur", "Sorcier", "Magicien"}'),

('550e8400-e29b-41d4-a716-446655440016', 'Hâte', 3, 'Transmutation', '1 action', '9 mètres', '{"V": true, "S": true, "M": "un copeau de racine de réglisse"}', 'Concentration, jusqu''à 1 minute', 'Choisissez une créature volontaire que vous pouvez voir à portée. Jusqu''à la fin du sort, la vitesse de la cible est doublée, elle gagne un bonus de +2 à la CA, elle a un avantage aux jets de sauvegarde de Dextérité, et elle gagne une action supplémentaire à chacun de ses tours.', NULL, '{"Ensorceleur", "Magicien"}'),

('550e8400-e29b-41d4-a716-446655440017', 'Guérison de groupe', 3, 'Évocation', '1 action', '18 mètres', '{"V": true, "S": true, "M": null}', 'Instantané', 'Une vague d''énergie curative émane d''un point de votre choix à portée. Choisissez jusqu''à six créatures dans une sphère de 9 mètres de rayon centrée sur ce point. Chaque cible récupère des points de vie égaux à 3d8 + votre modificateur de caractéristique d''incantation. Ce sort n''a aucun effet sur les morts-vivants ou les créatures artificielles.', 'Quand vous lancez ce sort en utilisant un emplacement de sort de niveau 4 ou supérieur, les soins augmentent de 1d8 pour chaque niveau d''emplacement au-delà du niveau 3.', '{"Barde", "Clerc", "Druide"}'),

-- Level 4 Spells
('550e8400-e29b-41d4-a716-446655440018', 'Porte dimensionnelle', 4, 'Invocation', '1 action', '150 mètres', '{"V": true, "S": false, "M": null}', 'Instantané', 'Vous vous téléportez depuis votre position actuelle vers n''importe quel autre endroit à portée. Vous arrivez exactement à l''endroit désiré. Ce peut être un endroit que vous pouvez voir, un que vous pouvez visualiser, ou un que vous pouvez décrire en indiquant la distance et la direction, comme « 60 mètres vers le bas » ou « vers le nord-ouest, 90 mètres, en montant de 9 mètres ».', NULL, '{"Barde", "Ensorceleur", "Sorcier", "Magicien"}'),

('550e8400-e29b-41d4-a716-446655440019', 'Mur de feu', 4, 'Évocation', '1 action', '36 mètres', '{"V": true, "S": true, "M": "un petit morceau de phosphore"}', 'Concentration, jusqu''à 1 minute', 'Vous créez un mur de feu sur une surface solide à portée. Vous pouvez faire un mur droit de jusqu''à 18 mètres de long, 6 mètres de haut et 30 centimètres d''épaisseur, ou un mur en anneau de jusqu''à 6 mètres de diamètre, 6 mètres de haut et 30 centimètres d''épaisseur. Le mur est opaque et dure pendant la durée du sort.', 'Quand vous lancez ce sort en utilisant un emplacement de sort de niveau 5 ou supérieur, les dégâts augmentent de 1d8 pour chaque niveau d''emplacement au-delà du niveau 4.', '{"Druide", "Ensorceleur", "Magicien"}')

ON CONFLICT (id) DO NOTHING;